options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Paso 1: Build de la imagen Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/django-app', '.']

  # Paso 2: Push de la imagen a Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/django-app']

  # Paso 3: Crear el archivo .env dinámicamente
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cat << EOF > .env
        SECRET_KEY=${_SECRET_KEY}
        DEBUG=${_DEBUG}
        DB_NAME=${_DB_NAME}
        DB_USER=${_DB_USER}
        DB_PASSWORD=${_DB_PASSWORD}
        DB_HOST=/cloudsql/users-app-452718:us-central1:game-db
        DB_PORT=5432
        EOF

  # Paso 4: Despliegue de la app en Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'django-app',
      '--image', 'gcr.io/$PROJECT_ID/django-app',
      '--platform', 'managed',
      '--region', 'us-central1',
      '--allow-unauthenticated',
      '--add-cloudsql-instances=users-app-452718:us-central1:game-db',
      '--env-vars-file=.env'
    ]

substitutions:
  _SECRET_KEY: "django-insecure-kws$nv&a6xgm1%+o=)jd1f475v#095jdkrp4@qzi%jyy6&*us*"
  _DEBUG: "False"
  _DB_NAME: "games_db"
  _DB_USER: "admin"
  _DB_PASSWORD: "R4Vg7pLnstn+K#x"

images:
  - 'gcr.io/$PROJECT_ID/django-app'
