options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/django-app', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/django-app']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'django-app',
      '--image', 'gcr.io/$PROJECT_ID/django-app',
      '--platform', 'managed',
      '--region', 'us-central1',
      '--allow-unauthenticated',
      '--add-cloudsql-instances=users-app-452718:us-central1:game-db',
      '--set-env-vars=SECRET_KEY=django-insecure-kws$nv&a6xgm1%+o=)jd1f475v#095jdkrp4@qzi%jyy6&*us*,DEBUG=False,DB_NAME=games_db,DB_USER=admin,DB_PASSWORD=`_H-{uO57<,C2g]#,DB_HOST=/cloudsql/users-app-452718:us-central1:game-db,DB_PORT=5432'
    ]
