# Generated by Django 5.1.7 on 2025-03-13 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_1_wins', models.IntegerField(default=0)),
                ('player_2_wins', models.IntegerField(default=0)),
                ('is_finished', models.BooleanField(default=False)),
                (
                    'player_1',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='games_as_player_1', to='game.player'
                    ),
                ),
                (
                    'player_2',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='games_as_player_2', to='game.player'
                    ),
                ),
                (
                    'winner',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='games_won',
                        to='game.player',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'player_1_move',
                    models.CharField(
                        blank=True,
                        choices=[('rock', 'Rock'), ('paper', 'Paper'), ('scissors', 'Scissors')],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    'player_2_move',
                    models.CharField(
                        blank=True,
                        choices=[('rock', 'Rock'), ('paper', 'Paper'), ('scissors', 'Scissors')],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    'game',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='game.game'
                    ),
                ),
                (
                    'winner',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='rounds_won',
                        to='game.player',
                    ),
                ),
            ],
        ),
    ]
