name: Django Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U user -d test_db"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install PostgreSQL Client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Check PostgreSQL Container IP
        run: |
          IP_ADDRESS=$(docker inspect $(docker ps -q --filter "name=postgres") | grep IPAddress | awk '{print $2}' | tr -d '",')
          echo "DB_HOST=$IP_ADDRESS" >> $GITHUB_ENV
          echo "PostgreSQL IP Address: $IP_ADDRESS"

      - name: Set environment variables
        run: |
          echo "DJANGO_SETTINGS_MODULE=games.settings" >> $GITHUB_ENV
          echo "SECRET_KEY=django-insecure" >> $GITHUB_ENV
          echo "DEBUG=True" >> $GITHUB_ENV
          echo "DB_NAME=test_db" >> $GITHUB_ENV
          echo "DB_USER=user" >> $GITHUB_ENV
          echo "DB_PASSWORD=password" >> $GITHUB_ENV
          echo "DB_PORT=5432" >> $GITHUB_ENV

      - name: Wait for PostgreSQL to be ready
        run: |
          for i in {1..20}; do
            pg_isready -h $DB_HOST -p 5432 -U user && echo "PostgreSQL is ready" && exit 0
            echo "Waiting for PostgreSQL..." && sleep 5
          done
          echo "PostgreSQL did not become ready in time" && exit 1

      - name: Debug Information
        run: |
          docker ps
          docker network inspect github_network

      - name: Run migrations
        run: python manage.py migrate

      - name: Run tests
        run: python manage.py test
